//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion
    {
        public string idcotizacion { get; set; }
        public string idproveedor { get; set; }
        public string empresa_nom { get; set; }
        public System.DateTime fecha { get; set; }
        public string iddetcotizacion { get; set; }
    
        public virtual DetCotizacion DetCotizacion { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
