//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocVenta
    {
        public string iddocventa { get; set; }
        public System.DateTime fecha { get; set; }
        public string iddetdocventa { get; set; }
        public string idboleta { get; set; }
        public string idfactura { get; set; }
        public string idcliente { get; set; }
    
        public virtual boleta boleta { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual DetDocVenta DetDocVenta { get; set; }
        public virtual factura factura { get; set; }
    }
}
