//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuiaEntrada
    {
        public string idguiaentrada { get; set; }
        public System.DateTime fecha { get; set; }
        public string moneda { get; set; }
        public string estatus { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
        public string observacion { get; set; }
        public string nombre_autorizante { get; set; }
        public string iddetguiaentrada { get; set; }
    
        public virtual DetGuiaEntrada DetGuiaEntrada { get; set; }
    }
}
