//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuiaSalida
    {
        public string idguiasalida { get; set; }
        public System.DateTime fecha { get; set; }
        public string moneda { get; set; }
        public string nombre_autorizante { get; set; }
        public string iddetguiasalida { get; set; }
        public string idcliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual DetGuiaSalida DetGuiaSalida { get; set; }
    }
}
