//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextEntities : DbContext
    {
        public ContextEntities()
            : base("name=ContextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<boleta> boletas { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Cotizacion> Cotizacions { get; set; }
        public virtual DbSet<DetCotizacion> DetCotizacions { get; set; }
        public virtual DbSet<DetDocVenta> DetDocVentas { get; set; }
        public virtual DbSet<DetFacturaComp> DetFacturaComps { get; set; }
        public virtual DbSet<DetGuiaEntrada> DetGuiaEntradas { get; set; }
        public virtual DbSet<DetGuiaEntradaC> DetGuiaEntradaCs { get; set; }
        public virtual DbSet<DetGuiaSalida> DetGuiaSalidas { get; set; }
        public virtual DbSet<DetInventario> DetInventarios { get; set; }
        public virtual DbSet<DetOrdenComp> DetOrdenComps { get; set; }
        public virtual DbSet<DetPedidoComp> DetPedidoComps { get; set; }
        public virtual DbSet<DetProdFaltante> DetProdFaltantes { get; set; }
        public virtual DbSet<DocVenta> DocVentas { get; set; }
        public virtual DbSet<factura> facturas { get; set; }
        public virtual DbSet<FacturaComp> FacturaComps { get; set; }
        public virtual DbSet<GuiaEntrada> GuiaEntradas { get; set; }
        public virtual DbSet<GuiaEntradaC> GuiaEntradaCs { get; set; }
        public virtual DbSet<GuiaSalida> GuiaSalidas { get; set; }
        public virtual DbSet<Inventario> Inventarios { get; set; }
        public virtual DbSet<OrdenComp> OrdenComps { get; set; }
        public virtual DbSet<PedidoComp> PedidoComps { get; set; }
        public virtual DbSet<ProdFaltante> ProdFaltantes { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<TipoEmpleado> TipoEmpleadoes { get; set; }
        public virtual DbSet<Trabajador> Trabajadors { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
