//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DetCotizacions = new HashSet<DetCotizacion>();
            this.DetDocVentas = new HashSet<DetDocVenta>();
            this.DetFacturaComps = new HashSet<DetFacturaComp>();
            this.DetGuiaEntradas = new HashSet<DetGuiaEntrada>();
            this.DetGuiaEntradaCs = new HashSet<DetGuiaEntradaC>();
            this.DetGuiaEntradaCs1 = new HashSet<DetGuiaEntradaC>();
            this.DetGuiaSalidas = new HashSet<DetGuiaSalida>();
            this.DetInventarios = new HashSet<DetInventario>();
            this.DetOrdenComps = new HashSet<DetOrdenComp>();
            this.DetPedidoComps = new HashSet<DetPedidoComp>();
            this.DetProdFaltantes = new HashSet<DetProdFaltante>();
        }
    
        public string idproducto { get; set; }
        public string nombre { get; set; }
        public string categoria { get; set; }
        public string descripcion { get; set; }
        public decimal preciounidad { get; set; }
        public decimal precioventa { get; set; }
        public int unidadesstock { get; set; }
        public int unidadesorden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetCotizacion> DetCotizacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetDocVenta> DetDocVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetFacturaComp> DetFacturaComps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetGuiaEntrada> DetGuiaEntradas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetGuiaEntradaC> DetGuiaEntradaCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetGuiaEntradaC> DetGuiaEntradaCs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetGuiaSalida> DetGuiaSalidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetInventario> DetInventarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetOrdenComp> DetOrdenComps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetPedidoComp> DetPedidoComps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetProdFaltante> DetProdFaltantes { get; set; }
    }
}
