//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajador
    {
        public string idtrabajador { get; set; }
        public string id_usuario { get; set; }
        public string telefono { get; set; }
        public string edad { get; set; }
        public string direccion { get; set; }
        public string idtipoempleado { get; set; }
    
        public virtual TipoEmpleado TipoEmpleado { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
